# Generated by Django 3.0.8 on 2020-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
