# Generated by Django 3.0.8 on 2020-07-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
