# Generated by Django 3.0.8 on 2020-07-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200712_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
    ]
