# Generated by Django 3.0.8 on 2020-07-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Thread')),
            ],
        ),
    ]
