# Generated by Django 3.0.8 on 2020-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_threaditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='threads',
            field=models.ManyToManyField(related_name='posts', through='blog.ThreadItem', to='blog.Thread'),
        ),
    ]
